[Writable]
LogLevel = "INFO"
  # Example InsecureSecrets configuration that simulates SecretStore for when EDGEX_SECURITY_SECRET_STORE=false
  # InsecureSecrets are required for when Redis is used for message bus
  [Writable.InsecureSecrets]
    [Writable.InsecureSecrets.DB]
    path = "redisdb"
      [Writable.InsecureSecrets.DB.Secrets]
      username = ""
      password = ""

    [Writable.InsecureSecrets.credentials001]
    path = "credentials001"
      [Writable.InsecureSecrets.credentials001.Secrets]
      username = ""
      password = ""
      mode = "usernametoken" # assign "digest" | "usernametoken" | "both" | "none"

    [Writable.InsecureSecrets.credentials002]
    path = "credentials002"
      [Writable.InsecureSecrets.credentials002.Secrets]
      username = ""
      password = ""
      mode = "usernametoken" # assign "digest" | "usernametoken" | "both" | "none"

[Service]
HealthCheckInterval = "10s"
Host = "localhost"
Port = 59984
ServerBindAddr = ""  # blank value defaults to Service.Host value
StartupMsg = "Camera device service started"
# MaxRequestSize limit the request body size in byte of put command
MaxRequestSize = 0 # value 0 unlimit the request size.
RequestTimeout = "5s"
  [Service.CORSConfiguration]
  EnableCORS = false
  CORSAllowCredentials = false
  CORSAllowedOrigin = "https://localhost"
  CORSAllowedMethods = "GET, POST, PUT, PATCH, DELETE"
  CORSAllowedHeaders = "Authorization, Accept, Accept-Language, Content-Language, Content-Type, X-Correlation-ID"
  CORSExposeHeaders = "Cache-Control, Content-Language, Content-Length, Content-Type, Expires, Last-Modified, Pragma, X-Correlation-ID"
  CORSMaxAge = 3600

# Only used when EDGEX_SECURITY_SECRET_STORE=true which is now required for secure consul
# Must also add `ADD_SECRETSTORE_TOKENS: "device-onvif-camera"`  and  `ADD_KNOWN_SECRETS: redisdb[device-onvif-camera]` to secret-store-setup environment so it generates  the token and secret store in vault for 'device-onvif-camera' and added the Redis credentials
[SecretStore]
Type = "vault"
Host = "localhost"
Port = 8200
Path = "device-onvif-camera/"
Protocol = "http"
RootCaCertPath = ""
ServerName = ""
TokenFile = "/tmp/edgex/secrets/device-onvif-camera/secrets-token.json"
  [SecretStore.Authentication]
  AuthType = "X-Vault-Token"

[Registry]
Type = "consul"
Host = "localhost"
Port = 8500

[Clients]
  [Clients.core-data]
  Protocol = "http"
  Host = "localhost"
  Port = 59880

  [Clients.core-metadata]
  Protocol = "http"
  Host = "localhost"
  Port = 59881

[MessageQueue]
Protocol = "redis"
Host = "localhost"
Port = 6379
Type = "redis"
AuthMode = "usernamepassword"  # required for redis messagebus (secure or insecure).
SecretName = "redisdb"
PublishTopicPrefix = "edgex/events/device" # /<device-profile-name>/<device-name>/<source-name> will be added to this Publish Topic prefix
  [MessageQueue.Optional]
  # Default MQTT Specific options that need to be here to enable environment variable overrides of them
  # Client Identifiers
  ClientId = "device-onvif-camera"
  # Connection information
  Qos = "0" # Quality of Sevice values are 0 (At most once), 1 (At least once) or 2 (Exactly once)
  KeepAlive = "10" # Seconds (must be 2 or greater)
  Retained = "false"
  AutoReconnect = "true"
  ConnectTimeout = "5" # Seconds
  SkipCertVerify = "false" # Only used if Cert/Key file or Cert/Key PEMblock are specified

[Device]
DataTransform = true
MaxCmdOps = 128
MaxCmdValueLen = 256
ProfilesDir = "./res/profiles"
DevicesDir = "./res/devices"
UpdateLastConnected = false
EnableAsyncReadings = true
AsyncBufferSize = 16
Labels = []
UseMessageBus = true
  [Device.Discovery]
  Enabled = true
  Interval = "1h"

# Custom configs
[AppCustom]
# The number of seconds to wait when making an Onvif request before timing out
RequestTimeout = 5 # Seconds

# The Secret Path of the default credentials to use for devices which do not have MAC Addresses defined, or do not
# have credentials defined in the CredentialsMap. The magic value of 'NoAuth' here will cause the devices to default
# to not using any authentication. If authentication is required, it would then need to be manually configured.
DefaultSecretPath = "credentials001"

# BaseNotificationURL indicates the device service network location (which should be accessible from onvif devices on the network), when
# configuring an Onvif Event subscription.
BaseNotificationURL = "http://192.168.12.112:59984"

# Select which discovery mechanism(s) to use
DiscoveryMode = "both" # netscan, multicast, or both

# The target ethernet interface for multicast discovering
DiscoveryEthernetInterface = "eth0"

# List of IPv4 subnets to perform netscan discovery on, in CIDR format (X.X.X.X/Y)
# separated by commas ex: "192.168.1.0/24,10.0.0.0/24"
DiscoverySubnets = ""

# Maximum simultaneous network probes when running netscan discovery.
ProbeAsyncLimit = 4000

# Maximum amount of milliseconds to wait for each IP probe before timing out.
# This will also be the minimum time the discovery process can take.
ProbeTimeoutMillis = 2000

# Maximum amount of seconds the discovery process is allowed to run before it will be cancelled.
# It is especially important to have this configured in the case of larger subnets such as /16 and /8
MaxDiscoverDurationSeconds = 300

# Enable or disable the built in status checking of devices, which runs every CheckStatusInterval.
EnableStatusCheck = true

# The interval in seconds at which the service will check the connection of all known cameras and update the device status 
# A longer interval will mean the service will detect changes in status less quickly
# Maximum 300s (5 minutes)
CheckStatusInterval = 30

# The location of Provision Watcher json files to import when using auto-discovery
ProvisionWatcherDir = "res/provision_watchers"

  # AppCustom.CredentialsMap is a map of SecretPath -> Comma separated list of mac addresses
  #
  # Example: (Single mapping for 1 mac address to 1 credential)
  #   credentials001 = "aa:bb:cc:dd:ee:ff"
  #
  # Example: (Multi mapping for 3 mac address to 1 shared credentials)
  #   credentials002 = "11:22:33:44:55:66,ff:ee:dd:cc:bb:aa,ab:12:12:34:34:56:56"
  #
  # The special group 'NoAuth' defines mac addresses of cameras where no authentication is to be used. This
  # group will cause the code to skip looking in the SecretStore altogether. 'NoAuth' is a special group
  # name that does not exist in the SecretStore.
  [AppCustom.CredentialsMap]
  NoAuth = ""
